export const UPDATE_USER="UPDATE_USER"
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const UPDATE_FEED="UPDATE_FEED";
export const SET_SELECTED_USER="SET_SELECTED_USER"
export const LIKE_UNLIKE_POST="LIKE_UNLIKE_POST"
export const ADD_POST="ADD_POST"
export const DELETE_POST="DELETE_POST"
export const DELETE_COMMENT="DELETE_COMMENT"
export const LIKE_UNLIKE_COMMENT="LIKE_UNLIKE_COMMENT"
export const ADD_COMMENT="ADD_COMMENT"
export const SET_EXPLORE="SET_EXPLORE"
export const ADD_EXPLORE="ADD_EXPLORE"
export const SEND_FOLLOW_REQUEST="SEND_FOLLOW_REQUEST"
export const SET_RECOMMENDED="SET_RECOMMENDED"
export const RESET_USER_PROFILE="RESET_USER_PROFILE"