export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const FINISH_LOADING= "FINISH_LOADING"
export const LOG_OUT="LOG_OUT"
export const UPDATE_USER="UPDATE_USER"
export const UNFOLLOW="UNFOLLOW"
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const ACCEPT_REQUEST="ACCEPT_REQUEST";
export const DECLINE_REQUEST="DECLINE_REQUEST"
export const UPDATE_BIO="UPDATE_BIO"
export const UPDATE_PROFILE_PIC="UPDATE_PROFILE_PIC"